name: Install Nginx on EC2

on: 
  push:           # This workflow will run on every push to the repository
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (though not mandatory for this task)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setting up SSH access to the EC2 instance
      - name: Install Nginx on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8    # Use SSH Action to run commands on EC2
        with:
          host: 52.76.3.196                 # Public IP of your EC2 instance
          username: ubuntu                  # Default username for EC2 (change if necessary)
          key: ${{ secrets.EC2_SSH_KEY }}   # Use the correct secret name here
          port: 22
          script: |
            sudo apt update                 # Update the package list
            sudo apt install -y nginx       # Install Nginx
            sudo systemctl start nginx      # Start Nginx service
            sudo systemctl enable nginx     # Enable Nginx to start on boot
