name: Install Nginx on EC2

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 

      - name: Debug Secrets
        run: |
          echo "SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'"
          echo "SSH_HOST: '${{ secrets.SSH_HOST }}'"
          echo "USER_NAME: '${{ secrets.USER_NAME }}'"

      - name: Build & Deploy
        run: |
          PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
          HOSTNAME="${{ secrets.SSH_HOST }}"
          USER_NAME="${{ secrets.USER_NAME }}"
          
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          echo "Attempting to SSH into $HOSTNAME as $USER_NAME"
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo systemctl status nginx
          EOF
