name: Install Nginx on EC2

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nginx on EC2 via SSH
        uses: appleboy/ssh-action@vv0.1.12
        with:
          host: 52.76.3.196
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # Correct reference to the secret
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
