name: Install Nginx on EC2

on: 
  push:
    branches: 
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Debug Secrets (Optional)
        if: always()  # Run even if the workflow fails
        run: |
          echo "SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'"
          echo "SSH_HOST: '${{ secrets.SSH_HOST }}'"
          echo "USER_NAME: '${{ secrets.USER_NAME }}'"

      - name: Build & Deploy
        run: |
          PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
          HOSTNAME="${{ secrets.SSH_HOST }}"
          USER_NAME="${{ secrets.USER_NAME }}"
          
          # Save private key to a file and set the correct permissions
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          # Attempt to SSH and install Nginx
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo systemctl status nginx
          EOF

          # Remove the private key after use for security
          rm -f private_key
