name: Setup EC2 Instance with Nginx

on:
  push:           # Trigger on every push to the main branch
    branches:
      - main

jobs:
  setup-ec2:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional step)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to start the AWS EC2 instance
      - name: Start AWS EC2
        id: start_ec2
        run: |
          instance_id="${{ secrets.AWS_EC2_INSTANCE_ID }}"
          aws ec2 start-instances --instance-ids "$instance_id"
          echo "Started EC2 Instance: $instance_id"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      # Step to create an EC2 instance with user data to install Nginx
      - name: Install Nginx via User Data
        run: |
          instance_id="${{ secrets.AWS_EC2_INSTANCE_ID }}"
          user_data='#!/bin/bash
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx'
          
          # Run the user data script
          aws ec2 modify-instance-attribute --instance-id "$instance_id" --user-data "Value=$(echo $user_data | base64)"
          echo "Nginx installation commands set in user data for instance: $instance_id"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
